info:
  component: Turbine

PREFIX:

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: ${PORT:8989}

management:
  port: 8990

#turbine:
#  amqp:
#    port: ${PORT:8989}

turbine:
  appConfig: fortunes,ui
  aggregator:
    clusterConfig: FORTUNES

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://localhost:8761}/eureka/

---
spring:
  profiles: cloud
management:
  port: -1
